FROM nginx:alpine

# Create the directory
RUN mkdir -p /var/www/public

# Copy the config file
COPY nginx-prod.conf /etc/nginx/conf.d/default.conf

# Copy the public folder and set permissions
COPY public /var/www/public

# Ensure Nginx has permissions to read the files
RUN chown -R nginx:nginx /var/www/public && chmod -R 755 /var/www/public

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
