FROM nginx:alpine

# Create the directory
RUN mkdir -p /var/www/public

# Copy the config file
COPY nginx-prod.conf /etc/nginx/conf.d/default.conf

# Copy the public folder from your project to the container
COPY public /var/www/public

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
